### ISSUE TITLE
CI: Clang format detects lens.h as Objective-C

### ISSUE THREAD

**Issue by joeltio** [joeltio/bento-box#42]
When running Clang format in CLion on `sim/lib/core/include/core/optics/lens.h` on branch `feat/engine-array-index`, I get this error 
![Configuration file(s) do(es) not support Objective-C: .clangformat](https://user-images.githubusercontent.com/5127468/107370011-68b75100-6b1d-11eb-983f-2ff200b87742.png)

This also fails linting when run on the CI.

**Comment by mrzzy** [comment]
From the [Clang Format Docs](https://clang.llvm.org/docs/ClangFormatStyleOptions.html)

> When clang-format formats a file, it auto-detects the language using the file name. 

So to make it unambiguous that `lens.h` is C++ to `clang-format` , we can rename it  to `lens.hpp`.

**Comment by joeltio** [comment]
This seems to have resolved the issue.

**Comment by mrzzy** [comment]
Reopening, as this fix seems to have [broken the CI](https://github.com/joeltio/bento-box/runs/1868922100?check_suite_focus=true#step:6:959)

**Comment by joeltio** [comment]
I doubt that the fix has broken the CI as there are a couple of other fixes I have not committed which may have broken the CI.

We'll have to wait until `feat/engine-array-index` is more stable.

**Comment by mrzzy** [comment]
Yeah the [errors](https://github.com/joeltio/bento-box/runs/1868922100?check_suite_focus=true#step:6:764) seem to be due to the new Protobuf changes:
```
../src/interpreter/operations.cpp:88:22: error: 'const class bento::protos::Node_Retrieve' has no member named 'retrieve_attr'; did you mean 'retrieve_value'?
   88 |     auto& ref = node.retrieve_attr();
      |                      ^~~~~~~~~~~~~
      |                      retrieve_value
../src/interpreter/operations.cpp: In function 'void interpreter::mutateOp(ics::ComponentStore&, ics::index::IndexStore&, const bento::protos::Node_Mutate&)':
../src/interpreter/operations.cpp:103:22: error: 'const class bento::protos::Node_Mutate' has no member named 'mutate_attr'
  103 |     auto& ref = node.mutate_attr();
      |                      ^~~~~~~~~~~
```

Closing.
